name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - master

jobs:
  node-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test

  deno-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        deno: ['v1.4', 'v1.5', 'v1.x', 'nightly']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run tests
        run: yarn test:deno
